<option value=""></option>
<option <?php if ($accr == "Contact Description") { echo " selected"; } ?> value="Contact Description"><?php echo get_field_config_contacts($dbc, 'Contact Description', 'order', $contype, $subtab); ?> : Contact Description <?php $cur_tab = get_field_config_contacts($dbc, 'Contact Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Site Information") { echo " selected"; } ?> value="Site Information"><?php echo get_field_config_contacts($dbc, 'Site Information', 'order', $contype, $subtab); ?> : Site Information <?php $cur_tab = get_field_config_contacts($dbc, 'Site Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vehicle Description") { echo " selected"; } ?> value="Vehicle Description"><?php echo get_field_config_contacts($dbc, 'Vehicle Description', 'order', $contype, $subtab); ?> : Vehicle Description <?php $cur_tab = get_field_config_contacts($dbc, 'Vehicle Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Location") { echo " selected"; } ?> value="Location"><?php echo get_field_config_contacts($dbc, 'Location', 'order', $contype, $subtab); ?> : Location <?php $cur_tab = get_field_config_contacts($dbc, 'Location', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Payment Description") { echo " selected"; } ?> value="Payment Description"><?php echo get_field_config_contacts($dbc, 'Payment Description', 'order', $contype, $subtab); ?> : Payment Description <?php $cur_tab = get_field_config_contacts($dbc, 'Payment Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Property Description") { echo " selected"; } ?> value="Property Description"><?php echo get_field_config_contacts($dbc, 'Property Description', 'order', $contype, $subtab); ?> : Property Description <?php $cur_tab = get_field_config_contacts($dbc, 'Property Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Contract/Form Info") { echo " selected"; } ?> value="Contract/Form Info"><?php echo get_field_config_contacts($dbc, 'Contract/Form Info', 'order', $contype, $subtab); ?> : Contract/Form Info <?php $cur_tab = get_field_config_contacts($dbc, 'Contract/Form Info', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Dates") { echo " selected"; } ?> value="Dates"><?php echo get_field_config_contacts($dbc, 'Dates', 'order', $contype, $subtab); ?> : Dates <?php $cur_tab = get_field_config_contacts($dbc, 'Dates', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Insurance") { echo " selected"; } ?> value="Insurance"><?php echo get_field_config_contacts($dbc, 'Insurance', 'order', $contype, $subtab); ?> : Insurance <?php $cur_tab = get_field_config_contacts($dbc, 'Insurance', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Comments") { echo " selected"; } ?> value="Comments"><?php echo get_field_config_contacts($dbc, 'Comments', 'order', $contype, $subtab); ?> : Comments <?php $cur_tab = get_field_config_contacts($dbc, 'Comments', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Staff Information") { echo " selected"; } ?> value="Staff Information"><?php echo get_field_config_contacts($dbc, 'Staff Information', 'order', $contype, $subtab); ?> : Staff Information <?php $cur_tab = get_field_config_contacts($dbc, 'Staff Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Staff Address") { echo " selected"; } ?> value="Staff Address"><?php echo get_field_config_contacts($dbc, 'Staff Address', 'order', $contype, $subtab); ?> : Staff Address <?php $cur_tab = get_field_config_contacts($dbc, 'Staff Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Staff Profile") { echo " selected"; } ?> value="Staff Profile"><?php echo get_field_config_contacts($dbc, 'Staff Profile', 'order', $contype, $subtab); ?> : Staff Profile <?php $cur_tab = get_field_config_contacts($dbc, 'Staff Profile', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Staff Bio") { echo " selected"; } ?> value="Staff Bio"><?php echo get_field_config_contacts($dbc, 'Staff Bio', 'order', $contype, $subtab); ?> : Staff Bio <?php $cur_tab = get_field_config_contacts($dbc, 'Staff Bio', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Employee Information") { echo " selected"; } ?> value="Employee Information"><?php echo get_field_config_contacts($dbc, 'Employee Information', 'order', $contype, $subtab); ?> : Employee Information <?php $cur_tab = get_field_config_contacts($dbc, 'Employee Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Direct Deposit Information") { echo " selected"; } ?> value="Direct Deposit Information"><?php echo get_field_config_contacts($dbc, 'Direct Deposit Information', 'order', $contype, $subtab); ?> : Direct Deposit Information <?php $cur_tab = get_field_config_contacts($dbc, 'Direct Deposit Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Emergency Contact") { echo " selected"; } ?> value="Emergency Contact"><?php echo get_field_config_contacts($dbc, 'Emergency Contact', 'order', $contype, $subtab); ?> : Emergency Contact <?php $cur_tab = get_field_config_contacts($dbc, 'Emergency Contact', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Primary Emergency Contact") { echo " selected"; } ?> value="Primary Emergency Contact"><?php echo get_field_config_contacts($dbc, 'Primary Emergency Contact', 'order', $contype, $subtab); ?> : Primary Emergency Contact <?php $cur_tab = get_field_config_contacts($dbc, 'Primary Emergency Contact', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Secondary Emergency Contact") { echo " selected"; } ?> value="Secondary Emergency Contact"><?php echo get_field_config_contacts($dbc, 'Secondary Emergency Contact', 'order', $contype, $subtab); ?> : Secondary Emergency Contact <?php $cur_tab = get_field_config_contacts($dbc, 'Secondary Emergency Contact', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Driver Information") { echo " selected"; } ?> value="Driver Information"><?php echo get_field_config_contacts($dbc, 'Driver Information', 'order', $contype, $subtab); ?> : Driver Information <?php $cur_tab = get_field_config_contacts($dbc, 'Driver Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vendor Information") { echo " selected"; } ?> value="Vendor Information"><?php echo get_field_config_contacts($dbc, 'Vendor Information', 'order', $contype, $subtab); ?> : Vendor Information <?php $cur_tab = get_field_config_contacts($dbc, 'Vendor Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vendor Address") { echo " selected"; } ?> value="Vendor Address"><?php echo get_field_config_contacts($dbc, 'Vendor Address', 'order', $contype, $subtab); ?> : Vendor Address <?php $cur_tab = get_field_config_contacts($dbc, 'Vendor Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Document Uploader") { echo " selected"; } ?> value="Document Uploader"><?php echo get_field_config_contacts($dbc, 'Document Uploader', 'order', $contype, $subtab); ?> : Document Uploader <?php $cur_tab = get_field_config_contacts($dbc, 'Document Uploader', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Contact Information") { echo " selected"; } ?> value="Contact Information"><?php echo get_field_config_contacts($dbc, 'Contact Information', 'order', $contype, $subtab); ?> : Contact Information <?php $cur_tab = get_field_config_contacts($dbc, 'Contact Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Contact Address") { echo " selected"; } ?> value="Contact Address"><?php echo get_field_config_contacts($dbc, 'Contact Address', 'order', $contype, $subtab); ?> : Contact Address <?php $cur_tab = get_field_config_contacts($dbc, 'Contact Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Business Information") { echo " selected"; } ?> value="Business Information"><?php echo get_field_config_contacts($dbc, 'Business Information', 'order', $contype, $subtab); ?> : Business Information <?php $cur_tab = get_field_config_contacts($dbc, 'Business Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Business Address") { echo " selected"; } ?> value="Business Address"><?php echo get_field_config_contacts($dbc, 'Business Address', 'order', $contype, $subtab); ?> : Business Address <?php $cur_tab = get_field_config_contacts($dbc, 'Business Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Owner Information") { echo " selected"; } ?> value="Owner Information"><?php echo get_field_config_contacts($dbc, 'Owner Information', 'order', $contype, $subtab); ?> : Owner Information <?php $cur_tab = get_field_config_contacts($dbc, 'Owner Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Owner Address") { echo " selected"; } ?> value="Owner Address"><?php echo get_field_config_contacts($dbc, 'Owner Address', 'order', $contype, $subtab); ?> : Owner Address <?php $cur_tab = get_field_config_contacts($dbc, 'Owner Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Tenant Information") { echo " selected"; } ?> value="Tenant Information"><?php echo get_field_config_contacts($dbc, 'Tenant Information', 'order', $contype, $subtab); ?> : Tenant Information <?php $cur_tab = get_field_config_contacts($dbc, 'Tenant Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Property Information") { echo " selected"; } ?> value="Property Information"><?php echo get_field_config_contacts($dbc, 'Property Information', 'order', $contype, $subtab); ?> : Property Information <?php $cur_tab = get_field_config_contacts($dbc, 'Property Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Financial Information") { echo " selected"; } ?> value="Financial Information"><?php echo get_field_config_contacts($dbc, 'Financial Information', 'order', $contype, $subtab); ?> : Financial Information <?php $cur_tab = get_field_config_contacts($dbc, 'Financial Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Lease Information") { echo " selected"; } ?> value="Lease Information"><?php echo get_field_config_contacts($dbc, 'Lease Information', 'order', $contype, $subtab); ?> : Lease Information <?php $cur_tab = get_field_config_contacts($dbc, 'Lease Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Mailing Contact") { echo " selected"; } ?> value="Mailing Contact"><?php echo get_field_config_contacts($dbc, 'Mailing Contact', 'order', $contype, $subtab); ?> : Mailing Contact <?php $cur_tab = get_field_config_contacts($dbc, 'Mailing Contact', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Mailing Address") { echo " selected"; } ?> value="Mailing Address"><?php echo get_field_config_contacts($dbc, 'Mailing Address', 'order', $contype, $subtab); ?> : Mailing Address <?php $cur_tab = get_field_config_contacts($dbc, 'Mailing Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Unit Information") { echo " selected"; } ?> value="Unit Information"><?php echo get_field_config_contacts($dbc, 'Unit Information', 'order', $contype, $subtab); ?> : Unit Information <?php $cur_tab = get_field_config_contacts($dbc, 'Unit Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Payment Information") { echo " selected"; } ?> value="Payment Information"><?php echo get_field_config_contacts($dbc, 'Payment Information', 'order', $contype, $subtab); ?> : Payment Information <?php $cur_tab = get_field_config_contacts($dbc, 'Payment Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Accounts Receivable/Credit on Account") { echo " selected"; } ?> value="Accounts Receivable/Credit on Account"><?php echo get_field_config_contacts($dbc, 'Accounts Receivable/Credit on Account', 'order', $contype, $subtab); ?> : Accounts Receivable/Credit on Account <?php $cur_tab = get_field_config_contacts($dbc, 'Accounts Receivable/Credit on Account', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Account Details") { echo " selected"; } ?> value="Account Details"><?php echo get_field_config_contacts($dbc, 'Account Details', 'order', $contype, $subtab); ?> : Account Details <?php $cur_tab = get_field_config_contacts($dbc, 'Account Details', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Account Statement") { echo " selected"; } ?> value="Account Statement"><?php echo get_field_config_contacts($dbc, 'Account Statement', 'order', $contype, $subtab); ?> : Account Statement <?php $cur_tab = get_field_config_contacts($dbc, 'Account Statement', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Patient Accounts Receivable") { echo " selected"; } ?> value="Patient Accounts Receivable"><?php echo get_field_config_contacts($dbc, 'Patient Accounts Receivable', 'order', $contype, $subtab); ?> : Patient Accounts Receivable <?php $cur_tab = get_field_config_contacts($dbc, 'Patient Accounts Receivable', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Insurer Accounts Receivable for Patient") { echo " selected"; } ?> value="Insurer Accounts Receivable for Patient"><?php echo get_field_config_contacts($dbc, 'Insurer Accounts Receivable for Patient', 'order', $contype, $subtab); ?> : Insurer Accounts Receivable for Patient <?php $cur_tab = get_field_config_contacts($dbc, 'Insurer Accounts Receivable for Patient', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "All Patient Invoices") { echo " selected"; } ?> value="All Patient Invoices"><?php echo get_field_config_contacts($dbc, 'All Patient Invoices', 'order', $contype, $subtab); ?> : All Patient Invoices <?php $cur_tab = get_field_config_contacts($dbc, 'All Patient Invoices', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "All Insurer Invoices for Patient") { echo " selected"; } ?> value="All Insurer Invoices for Patient"><?php echo get_field_config_contacts($dbc, 'All Insurer Invoices for Patient', 'order', $contype, $subtab); ?> : All Insurer Invoices for Patient <?php $cur_tab = get_field_config_contacts($dbc, 'All Insurer Invoices for Patient', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>


<option <?php if ($accr == "Social Media Links") { echo " selected"; } ?> value="Social Media Links"><?php echo get_field_config_contacts($dbc, 'Social Media Links', 'order', $contype, $subtab); ?> : Social Media Links <?php $cur_tab = get_field_config_contacts($dbc, 'Social Media Links', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Login Information") { echo " selected"; } ?> value="Login Information"><?php echo get_field_config_contacts($dbc, 'Login Information', 'order', $contype, $subtab); ?> : Login Information <?php $cur_tab = get_field_config_contacts($dbc, 'Login Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Software Access") { echo " selected"; } ?> value="Software Access"><?php echo get_field_config_contacts($dbc, 'Software Access', 'order', $contype, $subtab); ?> : Software Access <?php $cur_tab = get_field_config_contacts($dbc, 'Software Access', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Status") { echo " selected"; } ?> value="Status"><?php echo get_field_config_contacts($dbc, 'Status', 'order', $contype, $subtab); ?> : Status <?php $cur_tab = get_field_config_contacts($dbc, 'Status', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Client Information") { echo " selected"; } ?> value="Client Information"><?php echo get_field_config_contacts($dbc, 'Client Information', 'order', $contype, $subtab); ?> : Client Information <?php $cur_tab = get_field_config_contacts($dbc, 'Client Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Client Address") { echo " selected"; } ?> value="Client Address"><?php echo get_field_config_contacts($dbc, 'Client Address', 'order', $contype, $subtab); ?> : Client Address <?php $cur_tab = get_field_config_contacts($dbc, 'Client Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Division") { echo " selected"; } ?> value="Division"><?php echo get_field_config_contacts($dbc, 'Division', 'order', $contype, $subtab); ?> : Division <?php $cur_tab = get_field_config_contacts($dbc, 'Division', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Transportation") { echo " selected"; } ?> value="Transportation"><?php echo get_field_config_contacts($dbc, 'Transportation', 'order', $contype, $subtab); ?> : Transportation <?php $cur_tab = get_field_config_contacts($dbc, 'Transportation', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Health Care") { echo " selected"; } ?> value="Health Care"><?php echo get_field_config_contacts($dbc, 'Health Care', 'order', $contype, $subtab); ?> : Health Care <?php $cur_tab = get_field_config_contacts($dbc, 'Health Care', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Health Concerns") { echo " selected"; } ?> value="Health Concerns"><?php echo get_field_config_contacts($dbc, 'Health Concerns', 'order', $contype, $subtab); ?> : Health Concerns <?php $cur_tab = get_field_config_contacts($dbc, 'Health Concerns', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Company Benefits") { echo " selected"; } ?> value="Company Benefits"><?php echo get_field_config_contacts($dbc, 'Company Benefits', 'order', $contype, $subtab); ?> : Company Benefits <?php $cur_tab = get_field_config_contacts($dbc, 'Company Benefits', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Health Care - Insurance") { echo " selected"; } ?> value="Health Care - Insurance"><?php echo get_field_config_contacts($dbc, 'Health Care - Insurance', 'order', $contype, $subtab); ?> : Health Care & Insurance <?php $cur_tab = get_field_config_contacts($dbc, 'Health Care - Insurance', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Guardians") { echo " selected"; } ?> value="Guardians"><?php echo get_field_config_contacts($dbc, 'Guardians', 'order', $contype, $subtab); ?> : Guardians <?php $cur_tab = get_field_config_contacts($dbc, 'Guardians', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Trustee") { echo " selected"; } ?> value="Trustee"><?php echo get_field_config_contacts($dbc, 'Trustee', 'order', $contype, $subtab); ?> : Trustee <?php $cur_tab = get_field_config_contacts($dbc, 'Trustee', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Family Doctor") { echo " selected"; } ?> value="Family Doctor"><?php echo get_field_config_contacts($dbc, 'Family Doctor', 'order', $contype, $subtab); ?> : Family Doctor <?php $cur_tab = get_field_config_contacts($dbc, 'Family Doctor', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Dentist") { echo " selected"; } ?> value="Dentist"><?php echo get_field_config_contacts($dbc, 'Dentist', 'order', $contype, $subtab); ?> : Dentist <?php $cur_tab = get_field_config_contacts($dbc, 'Dentist', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Specialists") { echo " selected"; } ?> value="Specialists"><?php echo get_field_config_contacts($dbc, 'Specialists', 'order', $contype, $subtab); ?> : Specialists <?php $cur_tab = get_field_config_contacts($dbc, 'Specialists', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Diagnosis") { echo " selected"; } ?> value="Diagnosis"><?php echo get_field_config_contacts($dbc, 'Diagnosis', 'order', $contype, $subtab); ?> : Diagnosis <?php $cur_tab = get_field_config_contacts($dbc, 'Diagnosis', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Allergies") { echo " selected"; } ?> value="Allergies"><?php echo get_field_config_contacts($dbc, 'Allergies', 'order', $contype, $subtab); ?> : Allergies <?php $cur_tab = get_field_config_contacts($dbc, 'Allergies', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Equipment") { echo " selected"; } ?> value="Equipment"><?php echo get_field_config_contacts($dbc, 'Equipment', 'order', $contype, $subtab); ?> : Equipment <?php $cur_tab = get_field_config_contacts($dbc, 'Equipment', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "First Aid/CPR") { echo " selected"; } ?> value="First Aid/CPR"><?php echo get_field_config_contacts($dbc, 'First Aid/CPR', 'order', $contype, $subtab); ?> : First Aid/CPR <?php $cur_tab = get_field_config_contacts($dbc, 'First Aid/CPR', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Support Documents") { echo " selected"; } ?> value="Support Documents"><?php echo get_field_config_contacts($dbc, 'Support Documents', 'order', $contype, $subtab); ?> : Support Documents <?php $cur_tab = get_field_config_contacts($dbc, 'Support Documents', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Medications") { echo " selected"; } ?> value="Medications"><?php echo get_field_config_contacts($dbc, 'Medications', 'order', $contype, $subtab); ?> : Medications <?php $cur_tab = get_field_config_contacts($dbc, 'Medications', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Daily Log Notes") { echo " selected"; } ?> value="Daily Log Notes"><?php echo get_field_config_contacts($dbc, 'Daily Log Notes', 'order', $contype, $subtab); ?> : Daily Log Notes <?php $cur_tab = get_field_config_contacts($dbc, 'Daily Log Notes', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Management Comments") { echo " selected"; } ?> value="Management Comments"><?php echo get_field_config_contacts($dbc, 'Management Comments', 'order', $contype, $subtab); ?> : Management Comments <?php $cur_tab = get_field_config_contacts($dbc, 'Management Comments', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Seizure Protocols") { echo " selected"; } ?> value="Seizure Protocols"><?php echo get_field_config_contacts($dbc, 'Seizure Protocols', 'order', $contype, $subtab); ?> : Seizure <?php $cur_tab = get_field_config_contacts($dbc, 'Seizure Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Slip Fall Protocols") { echo " selected"; } ?> value="Slip Fall Protocols"><?php echo get_field_config_contacts($dbc, 'Slip Fall Protocols', 'order', $contype, $subtab); ?> : Slip & Fall <?php $cur_tab = get_field_config_contacts($dbc, 'Slip Fall Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Transfer Protocols") { echo " selected"; } ?> value="Transfer Protocols"><?php echo get_field_config_contacts($dbc, 'Transfer Protocols', 'order', $contype, $subtab); ?> : Transfer <?php $cur_tab = get_field_config_contacts($dbc, 'Transfer Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Toileting Protocols") { echo " selected"; } ?> value="Toileting Protocols"><?php echo get_field_config_contacts($dbc, 'Toileting Protocols', 'order', $contype, $subtab); ?> : Toileting <?php $cur_tab = get_field_config_contacts($dbc, 'Toileting Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Bathing Protocols") { echo " selected"; } ?> value="Bathing Protocols"><?php echo get_field_config_contacts($dbc, 'Bathing Protocols', 'order', $contype, $subtab); ?> : Bathing <?php $cur_tab = get_field_config_contacts($dbc, 'Bathing Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "G-Tube Protocols") { echo " selected"; } ?> value="G-Tube Protocols"><?php echo get_field_config_contacts($dbc, 'G-Tube Protocols', 'order', $contype, $subtab); ?> : G-Tube <?php $cur_tab = get_field_config_contacts($dbc, 'G-Tube Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Oxygen Protocols") { echo " selected"; } ?> value="Oxygen Protocols"><?php echo get_field_config_contacts($dbc, 'Oxygen Protocols', 'order', $contype, $subtab); ?> : Oxygen <?php $cur_tab = get_field_config_contacts($dbc, 'Oxygen Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Daily Log Notes Protocols") { echo " selected"; } ?> value="Daily Log Notes Protocols"><?php echo get_field_config_contacts($dbc, 'Daily Log Notes Protocols', 'order', $contype, $subtab); ?> : Daily Log Notes <?php $cur_tab = get_field_config_contacts($dbc, 'Daily Log Notes Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Comments Concerns Protocols") { echo " selected"; } ?> value="Comments Concerns Protocols"><?php echo get_field_config_contacts($dbc, 'Comments & Concerns Protocols', 'order', $contype, $subtab); ?> : Comments & Concerns <?php $cur_tab = get_field_config_contacts($dbc, 'Comments & Concerns Protocols', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Injury") { echo " selected"; } ?> value="Injury"><?php echo get_field_config_contacts($dbc, 'Injury', 'order', $contype, $subtab); ?> : Injury <?php $cur_tab = get_field_config_contacts($dbc, 'Injury', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>