<?php
$field_list = [
	'code' => 'Code',
	'category' => 'Category',
	'name' => 'Name',
	'product_name' => 'Product Name',
	'brand' => 'Brand',
	'sub_category' => 'Subcategory',
	'type' => 'Type',
	'color' => 'Color',
	'description' => 'Description',
	'application' => 'Application',
	'id_number' => 'ID #',
	'item_sku' => 'Item SKU',
	'part_no' => 'Part #',
	'gst_exempt' => 'GST Exempt',
	'cost' => 'Cost',
	'cdn_cpu' => 'CDN Cost Per Unit',
	'usd_cpu' => 'USD Cost Per Unit',
	'average_cost' => 'Average Cost',
	'purchase_cost' => 'Purchase Cost',
	'usd_invoice' => 'USD Invoice',
	'cogs_total' => 'COGS',
	'vendorid' => 'Vendor',
	'date_of_purchase' => 'Date of Purchase',
	'shipping_rate' => 'Shipping Rate',
	'shipping_cash' => 'Shipping Cash',
	'freight_charge' => 'Freight Charge',
	'exchange_rate' => 'Exchange Rate',
	'exchange_cash' => 'Exchange $',
	'pallet' => 'Pallet Num',
	'sell_price' => 'Sell Price',
	'final_retail_price' => 'Final Retail Price',
	'wholesale_price' => 'Wholesale Price',
	'commercial_price' => 'Commercial Price',
	'client_price' => 'Client Price',
	'purchase_order_price' => 'Purchase Order Price',
	'sales_order_price' => 'Sales Order Price',
	'suggested_retail_price' => 'Suggested Retail Price',
	'rush_price' => 'Rush Price',
	'include_in_so' => 'Include in Sales Order',
	'include_in_po' => 'Include in Purchase Orders',
	'include_in_pos' => 'Include in P.O.S.',
	'include_in_product' => 'Include in Product',
	'preferred_price' => 'Preferred Price',
	'admin_price' => 'Admin Price',
	'web_price' => 'Web Price',
	'commission_price' => 'Commission Price',
	'msrp' => 'MSRP',
	'unit_price' => 'Unit Price',
	'unit_cost' => 'Unit Cost',
	'markup' => 'Markup By $',
	'markup_perc' => 'Markup By %',
	'revenue' => 'GL Revenue',
	'asset' => 'GL Assets',
	'current_stock' => 'Current Stock',
	'current_inventory' => 'Current Inventory',
	'quantity' => 'Quantity',
	'expected_inventory' => 'Expected',
	'quantity#' => 'Receieved',
	'discrepency**NOCSV**' => 'Discrepency',
	'inv_variance' => 'Variance',
	'write_offs' => 'Write Offs',
	'buying_units' => 'Buying Units',
	'selling_units' => 'Selling Units',
	'stocking_units' => 'Stocking Units',
	'location' => 'Location',
	'lsd' => 'LSD',
	'size' => 'Size',
	'weight' => 'Weight',
	'gauge' => 'Gauge',
	'length' => 'Length',
	'pressure' => 'Pressure',
	'min_amount' => 'Min Amount',
	'max_amount' => 'Max Amount',
	'min_max' => 'Min Max',
	'min_bin' => 'Min Bin',
	'estimated_hours' => 'Estimated Hours',
	'actual_hours' => 'Actual Hours',
	'minimum_billable' => 'Minimum Billable',
	'quote_description' => 'Quote Description',
	'status' => 'Status',
	'display_website' => 'Display On Website',
	'featured' => 'Featured on Website',
	'new' => 'New Item',
	'sale' => 'Item On Sale',
	'clearance' => 'Item On Clearance',
	'note' => 'Notes',
	'comment' => 'Comments',
	'rent_price' => 'Rent Price',
	'drum_unit_cost' => 'Drum Unit Cost',
	'drum_unit_price' => 'Drum Unit Price',
	'tote_unit_cost' => 'Tote Unit Cost',
	'tote_unit_price' => 'Tote Unit Price',
	'wcb_price' => 'WCB Price',
	'rental_days' => 'Rental Days',
	'rental_weeks' => 'Rental Weeks',
	'rental_months' => 'Rental Months',
	'rental_years' => 'Rental Years',
	'reminder_alert' => 'Reminder/Alert',
	'daily' => 'Daily',
	'weekly' => 'Weekly',
	'monthly' => 'Monthly',
	'annually' => 'Annually',
	'total_days' => '#Of Days',
	'total_hours' => '#Of Hours',
	'total_km' => '#Of Kilometers',
	'total_miles' => '#Of Miles'
];

$is_money = [
	'cost',
	'cdn_cpu',
	'usd_cpu',
	'average_cost',
	'purchase_cost',
	'usd_invoice',
	'cogs_total',
	'shipping_cash',
	'freight_charge',
	'exchange_cash',
	'sell_price',
	'final_retail_price',
	'wholesale_price',
	'commercial_price',
	'client_price',
	'purchase_order_price',
	'sales_order_price',
	'suggested_retail_price',
	'rush_price',
	'preferred_price',
	'admin_price',
	'web_price',
	'commission_price',
	'msrp',
	'unit_price',
	'unit_cost',
	'markup',
	'revenue',
	'min_amount',
	'max_amount',
	'min_max',
	'min_bin',
	'minimum_billable',
	'rent_price',
	'drum_unit_cost',
	'drum_unit_price',
	'tote_unit_cost',
	'tote_unit_price',
	'wcb_price'
];

$ticket_field_list = [
	'purchase_order' => ['Ticket PO','PO #'],
	'ticket_label' => ['Ticket Label BOL','Bill of Lading']
];
?>