<?php $defined_holidays = [['label' => "New Year&#39;s Day", 'name' => "New Year&#39;s Day", 'day' => '1', 'week' => '', 'weekday' => '', 'month' => 'January', 'paid' => '1'],
	['label' => "Family Day (BC)", 'name' => "Family Day", 'day' => '', 'week' => '2', 'weekday' => 'Monday', 'month' => 'February', 'paid' => '1'],
	['label' => "Louis Riel Day (MB)", 'name' => "Louis Riel Day", 'day' => '', 'week' => '3', 'weekday' => 'Monday', 'month' => 'February', 'paid' => '1'],
	['label' => "Islander Day (PEI)", 'name' => "Islander Day", 'day' => '', 'week' => '3', 'weekday' => 'Monday', 'month' => 'February', 'paid' => '1'],
	['label' => "Family Day", 'name' => "Family Day", 'day' => '', 'week' => '3', 'weekday' => 'Monday', 'month' => 'February', 'paid' => '1'],
	['label' => "Heritage Day (NS)", 'name' => "Heritage Day", 'day' => '', 'week' => '3', 'weekday' => 'Monday', 'month' => 'February', 'paid' => '1'],
	['label' => "Saint Patrick&#39;s Day (NL)", 'name' => "Saint Patrick&#39;s Day", 'day' => '17', 'week' => '', 'weekday' => '', 'month' => 'March', 'paid' => '1'],
	['label' => "Good Friday", 'name' => "Good Friday", 'day' => '', 'week' => '', 'weekday' => '', 'month' => '', 'paid' => '1'],
	['label' => "Easter Sunday", 'name' => "Easter Sunday", 'day' => '', 'week' => '', 'weekday' => '', 'month' => '', 'paid' => '1'],
	['label' => "Easter Monday", 'name' => "Easter Monday", 'day' => '', 'week' => '', 'weekday' => '', 'month' => '', 'paid' => '1'],
	['label' => "Saint George&#39;s Day (NB)", 'name' => "Saint George&#39;s Day", 'day' => '23', 'week' => '', 'weekday' => '', 'month' => 'April', 'paid' => '1'],
	['label' => "National Patriots&#39; Day (QB)", 'name' => "National Patriots&#39; Day", 'day' => '', 'week' => '-2', 'weekday' => 'Monday', 'month' => 'May', 'paid' => '1'],
	['label' => "Victoria Day", 'name' => "Victoria Day", 'day' => '', 'week' => '-2', 'weekday' => 'Monday', 'month' => 'May', 'paid' => '1'],
	['label' => "National Aboriginal Day (NWT)", 'name' => "National Aboriginal Day", 'day' => '21', 'week' => '', 'weekday' => '', 'month' => 'June', 'paid' => '1'],
	['label' => "Discovery Day / National Holiday", 'name' => "Discovery Day / National Holiday", 'day' => '24', 'week' => '', 'weekday' => '', 'month' => 'June', 'paid' => '1'],
	['label' => "Canada Day", 'name' => "Canada Day", 'day' => '1', 'week' => '', 'weekday' => '', 'month' => 'July', 'paid' => '1'],
	['label' => "Orangemen&#39;s Day (NL)", 'name' => "Orangemen&#39;s Day", 'day' => '12', 'week' => '', 'weekday' => '', 'month' => 'July', 'paid' => '1'],
	['label' => "Civic Holiday", 'name' => "Civic Holiday", 'day' => '', 'week' => '1', 'weekday' => 'Monday', 'month' => 'August', 'paid' => '1'],
	['label' => "Heritage Day", 'name' => "Heritage Day", 'day' => '', 'week' => '1', 'weekday' => 'Monday', 'month' => 'August', 'paid' => '1'],
	['label' => "New Brunswick Day (NB)", 'name' => "New Brunswick Day", 'day' => '', 'week' => '1', 'weekday' => 'Monday', 'month' => 'August', 'paid' => '1'],
	['label' => "Natal Day (NS)", 'name' => "Natal Day", 'day' => '', 'week' => '1', 'weekday' => 'Monday', 'month' => 'August', 'paid' => '1'],
	['label' => "Gold Cup Parade Day (PEI)", 'name' => "Gold Cup Parade Day", 'day' => '', 'week' => '3', 'weekday' => 'Friday', 'month' => 'August', 'paid' => '1'],
	['label' => "Discovery Day (YT)", 'name' => "Discovery Day", 'day' => '', 'week' => '3', 'weekday' => 'Monday', 'month' => 'August', 'paid' => '1'],
	['label' => "Labour Day", 'name' => "Labour Day", 'day' => '', 'week' => '1', 'weekday' => 'Monday', 'month' => 'September', 'paid' => '1'],
	['label' => "Thanksgiving", 'name' => "Thanksgiving", 'day' => '', 'week' => '2', 'weekday' => 'Monday', 'month' => 'October', 'paid' => '1'],
	['label' => "Armistice Day (NL)", 'name' => "Armistice Day", 'day' => '11', 'week' => '', 'weekday' => '', 'month' => 'November', 'paid' => '1'],
	['label' => "Remembrance Day", 'name' => "Remembrance Day", 'day' => '11', 'week' => '', 'weekday' => '', 'month' => 'November', 'paid' => '1'],
	['label' => "Christmas Day", 'name' => "Christmas Day", 'day' => '25', 'week' => '', 'weekday' => '', 'month' => 'December', 'paid' => '1'],
	['label' => "Boxing Day", 'name' => "Boxing Day", 'day' => '26', 'week' => '', 'weekday' => '', 'month' => 'December', 'paid' => '1']];