<?php
/*
Dashboard
*/
include ('../include.php');

?>
</head>
<body>

<?php include ('../navigation.php'); ?>

<div class="container">
	<div class="row">

    <?php

        $abcd = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

        foreach($abcd as $table_name) {
            mysqli_query($dbc,"CREATE TABLE IF NOT EXISTS `contacts_fn_".$table_name."` (
          `contactid` int(11) NOT NULL,
		  `category` varchar(500) DEFAULT NULL,
		  `category_contact` varchar(200) DEFAULT NULL,
		  `name` varchar(300) DEFAULT NULL,
		  `status` varchar(10) DEFAULT 'Active',
		  `first_name` varchar(1000) NOT NULL,
		  `last_name` varchar(1000) DEFAULT NULL,
		  `office_phone` varchar(500) DEFAULT NULL,
		  `cell_phone` varchar(500) DEFAULT NULL,
		  `home_phone` varchar(500) DEFAULT NULL,
		  `fax` varchar(500) DEFAULT NULL,
		  `gender` varchar(50) DEFAULT NULL,
		  `email_address` varchar(1000) DEFAULT NULL,
		  `occupation` varchar(200) DEFAULT NULL,
		  `company` varchar(500) DEFAULT NULL,
		  `website` varchar(1000) DEFAULT NULL,
		  `license` varchar(200) DEFAULT NULL,
		  `plan_acctno` varchar(100) DEFAULT NULL,
		  `insurerid` varchar(50) DEFAULT NULL,
		  `hire_date` date DEFAULT NULL,
		  `probation_end_date` date DEFAULT NULL,
		  `probation_expiry_reminder_date` date DEFAULT NULL,
		  `probation_pay_rate` varchar(50) DEFAULT NULL,
		  `referred_by` varchar(200) DEFAULT NULL,
		  `referred_by_name` varchar(500) DEFAULT NULL,
		  `credential` varchar(200) DEFAULT NULL,
		  `health_care_no` varchar(1000) DEFAULT NULL,
		  `health_care_no_expiry` date DEFAULT NULL,
		  `birth_date` date DEFAULT NULL,
		  `scheduled_hours` varchar(500) DEFAULT NULL,
		  `schedule_days` varchar(200) DEFAULT NULL,
		  `correspondence_language` varchar(100) DEFAULT NULL,
		  `accepts_receive_emails` varchar(10) DEFAULT NULL,
		  `clinic_supplier_code` varchar(50) DEFAULT NULL,
		  `amount_to_bill` decimal(10,2) DEFAULT '0.00',
		  `amount_owing` decimal(10,2) DEFAULT '0.00',
		  `amount_credit` decimal(10,2) DEFAULT '0.00',
		  `pricing_level` varchar(200) DEFAULT NULL,
		  `since_date` date DEFAULT NULL,
		  `date_of_last_contact` date DEFAULT NULL,
		  `same_mail_address` int(2) DEFAULT NULL,
		  `same_ship_address` int(2) DEFAULT NULL,
		  `business_street` varchar(1000) DEFAULT NULL,
		  `business_city` varchar(500) DEFAULT NULL,
		  `business_state` varchar(500) DEFAULT NULL,
		  `business_country` varchar(500) DEFAULT NULL,
		  `business_zip` varchar(500) DEFAULT NULL,
		  `city_part` varchar(50) DEFAULT NULL,
		  `mail_street` varchar(1000) DEFAULT NULL,
		  `mail_city` varchar(500) DEFAULT NULL,
		  `mail_state` varchar(500) DEFAULT NULL,
		  `mail_country` varchar(500) DEFAULT NULL,
		  `mail_zip` varchar(500) DEFAULT NULL,
		  `ship_street` varchar(1000) DEFAULT NULL,
		  `ship_country` varchar(500) DEFAULT NULL,
		  `ship_city` varchar(500) DEFAULT NULL,
		  `ship_state` varchar(500) DEFAULT NULL,
		  `ship_zip` varchar(500) DEFAULT NULL,
		  `final_retail_price` varchar(50) DEFAULT NULL,
		  `admin_price` varchar(50) DEFAULT NULL,
		  `wholesale_price` varchar(50) DEFAULT NULL,
		  `commercial_price` varchar(50) DEFAULT NULL,
		  `client_price` varchar(50) DEFAULT NULL,
		  `minimum_billable` varchar(50) DEFAULT NULL,
		  `estimated_hours` varchar(50) DEFAULT NULL,
		  `actual_hours` varchar(50) DEFAULT NULL,
		  `msrp` varchar(50) DEFAULT NULL,
		  `hourly_rate` varchar(20) DEFAULT NULL,
		  `monthly_rate` varchar(50) DEFAULT NULL,
		  `semi_monthly_rate` varchar(50) DEFAULT NULL,
		  `daily_rate` varchar(50) DEFAULT NULL,
		  `hr_rate_work` varchar(50) DEFAULT NULL,
		  `hr_rate_travel` varchar(50) DEFAULT NULL,
		  `field_day_cost` varchar(50) DEFAULT NULL,
		  `field_day_billable` varchar(50) DEFAULT NULL,
		  `cost` varchar(20) DEFAULT NULL,
		  `description` text,
		  `quote_description` text,
		  `user_name` varchar(200) DEFAULT NULL,
		  `password` varchar(100) DEFAULT NULL,
		  `role` varchar(200) DEFAULT NULL,
		  `created_by` varchar(100) DEFAULT NULL,
		  `updated_at` date DEFAULT NULL,
		  `deleted` int(1) NOT NULL DEFAULT '0',
		  `new_patient` int(1) NOT NULL DEFAULT '0',
		  `toggle_tile_menu` varchar(555) DEFAULT NULL,
		  `software_tile_menu_choice` varchar(555) DEFAULT NULL,
		  `software_styler_choice` varchar(555) DEFAULT NULL,
		  `mva_forms` text,
		  `maintenance` int(1) NOT NULL DEFAULT '0',
		  `first_letter` varchar(10) DEFAULT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1");


        mysqli_query($dbc,"CREATE TABLE IF NOT EXISTS `contacts_ln_".$table_name."` (
          `contactid` int(11) NOT NULL,
		  `category` varchar(500) DEFAULT NULL,
		  `category_contact` varchar(200) DEFAULT NULL,
		  `name` varchar(300) DEFAULT NULL,
		  `status` varchar(10) DEFAULT 'Active',
		  `first_name` varchar(1000) NOT NULL,
		  `last_name` varchar(1000) DEFAULT NULL,
		  `office_phone` varchar(500) DEFAULT NULL,
		  `cell_phone` varchar(500) DEFAULT NULL,
		  `home_phone` varchar(500) DEFAULT NULL,
		  `fax` varchar(500) DEFAULT NULL,
		  `gender` varchar(50) DEFAULT NULL,
		  `email_address` varchar(1000) DEFAULT NULL,
		  `occupation` varchar(200) DEFAULT NULL,
		  `company` varchar(500) DEFAULT NULL,
		  `website` varchar(1000) DEFAULT NULL,
		  `license` varchar(200) DEFAULT NULL,
		  `plan_acctno` varchar(100) DEFAULT NULL,
		  `insurerid` varchar(50) DEFAULT NULL,
		  `hire_date` date DEFAULT NULL,
		  `probation_end_date` date DEFAULT NULL,
		  `probation_expiry_reminder_date` date DEFAULT NULL,
		  `probation_pay_rate` varchar(50) DEFAULT NULL,
		  `referred_by` varchar(200) DEFAULT NULL,
		  `referred_by_name` varchar(500) DEFAULT NULL,
		  `credential` varchar(200) DEFAULT NULL,
		  `health_care_no` varchar(1000) DEFAULT NULL,
		  `health_care_no_expiry` date DEFAULT NULL,
		  `birth_date` date DEFAULT NULL,
		  `scheduled_hours` varchar(500) DEFAULT NULL,
		  `schedule_days` varchar(200) DEFAULT NULL,
		  `correspondence_language` varchar(100) DEFAULT NULL,
		  `accepts_receive_emails` varchar(10) DEFAULT NULL,
		  `clinic_supplier_code` varchar(50) DEFAULT NULL,
		  `amount_to_bill` decimal(10,2) DEFAULT '0.00',
		  `amount_owing` decimal(10,2) DEFAULT '0.00',
		  `amount_credit` decimal(10,2) DEFAULT '0.00',
		  `pricing_level` varchar(200) DEFAULT NULL,
		  `since_date` date DEFAULT NULL,
		  `date_of_last_contact` date DEFAULT NULL,
		  `same_mail_address` int(2) DEFAULT NULL,
		  `same_ship_address` int(2) DEFAULT NULL,
		  `business_street` varchar(1000) DEFAULT NULL,
		  `business_city` varchar(500) DEFAULT NULL,
		  `business_state` varchar(500) DEFAULT NULL,
		  `business_country` varchar(500) DEFAULT NULL,
		  `business_zip` varchar(500) DEFAULT NULL,
		  `city_part` varchar(50) DEFAULT NULL,
		  `mail_street` varchar(1000) DEFAULT NULL,
		  `mail_city` varchar(500) DEFAULT NULL,
		  `mail_state` varchar(500) DEFAULT NULL,
		  `mail_country` varchar(500) DEFAULT NULL,
		  `mail_zip` varchar(500) DEFAULT NULL,
		  `ship_street` varchar(1000) DEFAULT NULL,
		  `ship_country` varchar(500) DEFAULT NULL,
		  `ship_city` varchar(500) DEFAULT NULL,
		  `ship_state` varchar(500) DEFAULT NULL,
		  `ship_zip` varchar(500) DEFAULT NULL,
		  `final_retail_price` varchar(50) DEFAULT NULL,
		  `admin_price` varchar(50) DEFAULT NULL,
		  `wholesale_price` varchar(50) DEFAULT NULL,
		  `commercial_price` varchar(50) DEFAULT NULL,
		  `client_price` varchar(50) DEFAULT NULL,
		  `minimum_billable` varchar(50) DEFAULT NULL,
		  `estimated_hours` varchar(50) DEFAULT NULL,
		  `actual_hours` varchar(50) DEFAULT NULL,
		  `msrp` varchar(50) DEFAULT NULL,
		  `hourly_rate` varchar(20) DEFAULT NULL,
		  `monthly_rate` varchar(50) DEFAULT NULL,
		  `semi_monthly_rate` varchar(50) DEFAULT NULL,
		  `daily_rate` varchar(50) DEFAULT NULL,
		  `hr_rate_work` varchar(50) DEFAULT NULL,
		  `hr_rate_travel` varchar(50) DEFAULT NULL,
		  `field_day_cost` varchar(50) DEFAULT NULL,
		  `field_day_billable` varchar(50) DEFAULT NULL,
		  `cost` varchar(20) DEFAULT NULL,
		  `description` text,
		  `quote_description` text,
		  `user_name` varchar(200) DEFAULT NULL,
		  `password` varchar(100) DEFAULT NULL,
		  `role` varchar(200) DEFAULT NULL,
		  `created_by` varchar(100) DEFAULT NULL,
		  `updated_at` date DEFAULT NULL,
		  `deleted` int(1) NOT NULL DEFAULT '0',
		  `new_patient` int(1) NOT NULL DEFAULT '0',
		  `toggle_tile_menu` varchar(555) DEFAULT NULL,
		  `software_tile_menu_choice` varchar(555) DEFAULT NULL,
		  `software_styler_choice` varchar(555) DEFAULT NULL,
		  `mva_forms` text,
		  `maintenance` int(1) NOT NULL DEFAULT '0',
		  `first_letter` varchar(10) DEFAULT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1");

        }

    echo 'Done';

    ?>

	</div>
</div>


<?php include ('../footer.php'); ?>