<?php
$field_list = [
    'service_type' => 'Service Type',
    'category' => 'Category',
    'heading' => 'Heading',
    'cost' => 'Cost',
    'service_image' => 'Service Image',
    'description' => 'Description',
    'quote_description' => 'Quote Description',
    'final_retail_price' => 'Final Retail Price',
    'admin_price' => 'Admin Price',
    'wholesale_price' => 'Wholesale Price',
    'commercial_price' => 'Commercial Price',
    'client_price' => 'Client Price',
    'minimum_billable' => 'Minimum Billable',
    'estimated_hours' => 'Estimated Hours',
    'actual_hours' => 'Actual Hours',
    'msrp' => 'MSRP',
    'service_code' => 'Service Code',
    'invoice_description' => 'Invoice Description',
    'ticket_description' => TICKET_NOUN.' Description',
    'name' => 'Name',
    'fee' => 'Fee',
    'unit_price' => 'Unit Price',
    'unit_cost' => 'Unit Cost',
    'rent_price' => 'Rent Price',
    'rental_days' => 'Rental Days',
    'rental_weeks' => 'Rental Weeks',
    'rental_months' => 'Rental Months',
    'rental_years' => 'Rental Years',
    'reminder_alert' => 'Reminder/Alert',
    'daily' => 'Daily',
    'weekly' => 'Weekly',
    'monthly' => 'Monthly',
    'annually' => 'Annually',
    'total_days' => '# of Days',
    'total_hours' => '# of Hours',
    'total_km' => '# of Kilometers',
    'total_miles' => '# of Miles',
    'hourly_rate' => 'Hourly Rate',
    'purchase_order_price' => 'Purchase Order Price',
    'sales_order_price' => 'Sales Order Price',
    'include_in_pos' => 'Include in Point of Sale',
    'include_in_po' => 'Include in Purchase Orders',
    'include_in_so' => 'Include in Sales Orders',
    'gst_exempt' => 'GST Exempt',
    'appointment_type' => 'Appointment Type',
    'quantity' => 'Quantity',
    'checklist' => 'Checklist'
];

$is_money = [
    'cost',
    'final_retail_price',
    'admin_price',
    'wholesale_price',
    'commercial_price',
    'client_price',
    'minimum_billable',
    'msrp',
    'fee',
    'unit_price',
    'unit_cost',
    'rent_price',
    'purchase_order_price',
    'sales_order_price'
];
?>