<option value=""></option>
<option <?php if ($accr == "Contact Description") { echo " selected"; } ?> value="Contact Description"><?php echo get_field_config_vendors($dbc, 'Contact Description', 'order', $contype, $subtab); ?> : Contact Description <?php $cur_tab = get_field_config_vendors($dbc, 'Contact Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Site Information") { echo " selected"; } ?> value="Site Information"><?php echo get_field_config_vendors($dbc, 'Site Information', 'order', $contype, $subtab); ?> : Site Information <?php $cur_tab = get_field_config_vendors($dbc, 'Site Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vehicle Description") { echo " selected"; } ?> value="Vehicle Description"><?php echo get_field_config_vendors($dbc, 'Vehicle Description', 'order', $contype, $subtab); ?> : Vehicle Description <?php $cur_tab = get_field_config_vendors($dbc, 'Vehicle Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Location") { echo " selected"; } ?> value="Location"><?php echo get_field_config_vendors($dbc, 'Location', 'order', $contype, $subtab); ?> : Location <?php $cur_tab = get_field_config_vendors($dbc, 'Location', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Payment Description") { echo " selected"; } ?> value="Payment Description"><?php echo get_field_config_vendors($dbc, 'Payment Description', 'order', $contype, $subtab); ?> : Payment Description <?php $cur_tab = get_field_config_vendors($dbc, 'Payment Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Property Description") { echo " selected"; } ?> value="Property Description"><?php echo get_field_config_vendors($dbc, 'Property Description', 'order', $contype, $subtab); ?> : Property Description <?php $cur_tab = get_field_config_vendors($dbc, 'Property Description', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Contract/Form Info") { echo " selected"; } ?> value="Contract/Form Info"><?php echo get_field_config_vendors($dbc, 'Contract/Form Info', 'order', $contype, $subtab); ?> : Contract/Form Info <?php $cur_tab = get_field_config_vendors($dbc, 'Contract/Form Info', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Dates") { echo " selected"; } ?> value="Dates"><?php echo get_field_config_vendors($dbc, 'Dates', 'order', $contype, $subtab); ?> : Dates <?php $cur_tab = get_field_config_vendors($dbc, 'Dates', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Insurance") { echo " selected"; } ?> value="Insurance"><?php echo get_field_config_vendors($dbc, 'Insurance', 'order', $contype, $subtab); ?> : Insurance <?php $cur_tab = get_field_config_vendors($dbc, 'Insurance', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Comments") { echo " selected"; } ?> value="Comments"><?php echo get_field_config_vendors($dbc, 'Comments', 'order', $contype, $subtab); ?> : Comments <?php $cur_tab = get_field_config_vendors($dbc, 'Comments', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Direct Deposit Information") { echo " selected"; } ?> value="Direct Deposit Information"><?php echo get_field_config_vendors($dbc, 'Direct Deposit Information', 'order', $contype, $subtab); ?> : Direct Deposit Information <?php $cur_tab = get_field_config_vendors($dbc, 'Direct Deposit Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Driver Information") { echo " selected"; } ?> value="Driver Information"><?php echo get_field_config_vendors($dbc, 'Driver Information', 'order', $contype, $subtab); ?> : Driver Information <?php $cur_tab = get_field_config_vendors($dbc, 'Driver Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vendor Information") { echo " selected"; } ?> value="Vendor Information"><?php echo get_field_config_vendors($dbc, 'Vendor Information', 'order', $contype, $subtab); ?> : <?= VENDOR_TILE ?> Information <?php $cur_tab = get_field_config_vendors($dbc, 'Vendor Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vendor Address") { echo " selected"; } ?> value="Vendor Address"><?php echo get_field_config_vendors($dbc, 'Vendor Address', 'order', $contype, $subtab); ?> : <?= VENDOR_TILE ?> Address <?php $cur_tab = get_field_config_vendors($dbc, 'Vendor Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Document Uploader") { echo " selected"; } ?> value="Document Uploader"><?php echo get_field_config_vendors($dbc, 'Document Uploader', 'order', $contype, $subtab); ?> : Document Uploader <?php $cur_tab = get_field_config_vendors($dbc, 'Document Uploader', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Contact Information") { echo " selected"; } ?> value="Contact Information"><?php echo get_field_config_vendors($dbc, 'Contact Information', 'order', $contype, $subtab); ?> : Contact Information <?php $cur_tab = get_field_config_vendors($dbc, 'Contact Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<!--<option <?php if ($accr == "Prefix") { echo " selected"; } ?> value="Prefix"><?php echo get_field_config_vendors($dbc, 'Prefix', 'order', $contype, $subtab); ?> : Prefix <?php $cur_tab = get_field_config_vendors($dbc, 'Prefix', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>-->
<option <?php if ($accr == "Contact Address") { echo " selected"; } ?> value="Contact Address"><?php echo get_field_config_vendors($dbc, 'Contact Address', 'order', $contype, $subtab); ?> : Contact Address <?php $cur_tab = get_field_config_vendors($dbc, 'Contact Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Business Information") { echo " selected"; } ?> value="Business Information"><?php echo get_field_config_vendors($dbc, 'Business Information', 'order', $contype, $subtab); ?> : Business Information <?php $cur_tab = get_field_config_vendors($dbc, 'Business Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Business Address") { echo " selected"; } ?> value="Business Address"><?php echo get_field_config_vendors($dbc, 'Business Address', 'order', $contype, $subtab); ?> : Business Address <?php $cur_tab = get_field_config_vendors($dbc, 'Business Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Owner Information") { echo " selected"; } ?> value="Owner Information"><?php echo get_field_config_vendors($dbc, 'Owner Information', 'order', $contype, $subtab); ?> : Owner Information <?php $cur_tab = get_field_config_vendors($dbc, 'Owner Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Owner Address") { echo " selected"; } ?> value="Owner Address"><?php echo get_field_config_vendors($dbc, 'Owner Address', 'order', $contype, $subtab); ?> : Owner Address <?php $cur_tab = get_field_config_vendors($dbc, 'Owner Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Tenant Information") { echo " selected"; } ?> value="Tenant Information"><?php echo get_field_config_vendors($dbc, 'Tenant Information', 'order', $contype, $subtab); ?> : Tenant Information <?php $cur_tab = get_field_config_vendors($dbc, 'Tenant Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Property Information") { echo " selected"; } ?> value="Property Information"><?php echo get_field_config_vendors($dbc, 'Property Information', 'order', $contype, $subtab); ?> : Property Information <?php $cur_tab = get_field_config_vendors($dbc, 'Property Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Financial Information") { echo " selected"; } ?> value="Financial Information"><?php echo get_field_config_vendors($dbc, 'Financial Information', 'order', $contype, $subtab); ?> : Financial Information <?php $cur_tab = get_field_config_vendors($dbc, 'Financial Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Lease Information") { echo " selected"; } ?> value="Lease Information"><?php echo get_field_config_vendors($dbc, 'Lease Information', 'order', $contype, $subtab); ?> : Lease Information <?php $cur_tab = get_field_config_vendors($dbc, 'Lease Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Mailing Contact") { echo " selected"; } ?> value="Mailing Contact"><?php echo get_field_config_vendors($dbc, 'Mailing Contact', 'order', $contype, $subtab); ?> : Mailing Contact <?php $cur_tab = get_field_config_vendors($dbc, 'Mailing Contact', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Mailing Address") { echo " selected"; } ?> value="Mailing Address"><?php echo get_field_config_vendors($dbc, 'Mailing Address', 'order', $contype, $subtab); ?> : Mailing Address <?php $cur_tab = get_field_config_vendors($dbc, 'Mailing Address', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Unit Information") { echo " selected"; } ?> value="Unit Information"><?php echo get_field_config_vendors($dbc, 'Unit Information', 'order', $contype, $subtab); ?> : Unit Information <?php $cur_tab = get_field_config_vendors($dbc, 'Unit Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Payment Information") { echo " selected"; } ?> value="Payment Information"><?php echo get_field_config_vendors($dbc, 'Payment Information', 'order', $contype, $subtab); ?> : Payment Information <?php $cur_tab = get_field_config_vendors($dbc, 'Payment Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Accounts Receivable/Credit on Account") { echo " selected"; } ?> value="Accounts Receivable/Credit on Account"><?php echo get_field_config_vendors($dbc, 'Accounts Receivable/Credit on Account', 'order', $contype, $subtab); ?> : Accounts Receivable/Credit on Account <?php $cur_tab = get_field_config_vendors($dbc, 'Accounts Receivable/Credit on Account', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Account Details") { echo " selected"; } ?> value="Account Details"><?php echo get_field_config_vendors($dbc, 'Account Details', 'order', $contype, $subtab); ?> : Account Details <?php $cur_tab = get_field_config_vendors($dbc, 'Account Details', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Account Statement") { echo " selected"; } ?> value="Account Statement"><?php echo get_field_config_vendors($dbc, 'Account Statement', 'order', $contype, $subtab); ?> : Account Statement <?php $cur_tab = get_field_config_vendors($dbc, 'Account Statement', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Vendor Accounts Receivable") { echo " selected"; } ?> value="Vendor Accounts Receivable"><?php echo get_field_config_vendors($dbc, 'Vendor Accounts Receivable', 'order', $contype, $subtab); ?> : <?= VENDOR_TILE ?> Accounts Receivable <?php $cur_tab = get_field_config_vendors($dbc, 'Vendor Accounts Receivable', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Insurer Accounts Receivable for Vendor") { echo " selected"; } ?> value="Insurer Accounts Receivable for Vendor"><?php echo get_field_config_vendors($dbc, 'Insurer Accounts Receivable for Vendor', 'order', $contype, $subtab); ?> : Insurer Accounts Receivable for Vendor <?php $cur_tab = get_field_config_vendors($dbc, 'Insurer Accounts Receivable for Vendor', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "All Vendor Invoices") { echo " selected"; } ?> value="All Vendor Invoices"><?php echo get_field_config_vendors($dbc, 'All Vendor Invoices', 'order', $contype, $subtab); ?> : All <?= VENDOR_TILE ?> Invoices <?php $cur_tab = get_field_config_vendors($dbc, 'All Vendor Invoices', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "All Insurer Invoices for Vendor") { echo " selected"; } ?> value="All Insurer Invoices for Vendor"><?php echo get_field_config_vendors($dbc, 'All Insurer Invoices for Vendor', 'order', $contype, $subtab); ?> : All Insurer Invoices for <?= VENDOR_TILE ?> <?php $cur_tab = get_field_config_vendors($dbc, 'All Insurer Invoices for Vendor', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Social Media Links") { echo " selected"; } ?> value="Social Media Links"><?php echo get_field_config_vendors($dbc, 'Social Media Links', 'order', $contype, $subtab); ?> : Social Media Links <?php $cur_tab = get_field_config_vendors($dbc, 'Social Media Links', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Login Information") { echo " selected"; } ?> value="Login Information"><?php echo get_field_config_vendors($dbc, 'Login Information', 'order', $contype, $subtab); ?> : Login Information <?php $cur_tab = get_field_config_vendors($dbc, 'Login Information', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Software Access") { echo " selected"; } ?> value="Software Access"><?php echo get_field_config_vendors($dbc, 'Software Access', 'order', $contype, $subtab); ?> : Software Access <?php $cur_tab = get_field_config_vendors($dbc, 'Software Access', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Status") { echo " selected"; } ?> value="Status"><?php echo get_field_config_vendors($dbc, 'Status', 'order', $contype, $subtab); ?> : Status <?php $cur_tab = get_field_config_vendors($dbc, 'Status', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Division") { echo " selected"; } ?> value="Division"><?php echo get_field_config_vendors($dbc, 'Division', 'order', $contype, $subtab); ?> : Division <?php $cur_tab = get_field_config_vendors($dbc, 'Division', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Transportation") { echo " selected"; } ?> value="Transportation"><?php echo get_field_config_vendors($dbc, 'Transportation', 'order', $contype, $subtab); ?> : Transportation <?php $cur_tab = get_field_config_vendors($dbc, 'Transportation', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Equipment") { echo " selected"; } ?> value="Equipment"><?php echo get_field_config_vendors($dbc, 'Equipment', 'order', $contype, $subtab); ?> : Equipment <?php $cur_tab = get_field_config_vendors($dbc, 'Equipment', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Support Documents") { echo " selected"; } ?> value="Support Documents"><?php echo get_field_config_vendors($dbc, 'Support Documents', 'order', $contype, $subtab); ?> : Support Documents <?php $cur_tab = get_field_config_vendors($dbc, 'Support Documents', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Management Comments") { echo " selected"; } ?> value="Management Comments"><?php echo get_field_config_vendors($dbc, 'Management Comments', 'order', $contype, $subtab); ?> : Management Comments <?php $cur_tab = get_field_config_vendors($dbc, 'Management Comments', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Profile Documents") { echo " selected"; } ?> value="Profile Documents"><?php echo get_field_config_vendors($dbc, 'Profile Documents', 'order', $contype, $subtab); ?> : Profile Documents <?php $cur_tab = get_field_config_vendors($dbc, 'Profile Documents', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>
<option <?php if ($accr == "Checklist") { echo " selected"; } ?> value="Checklist"><?php echo get_field_config_vendors($dbc, 'Checklist', 'order', $contype, $subtab); ?> : Checklist <?php $cur_tab = get_field_config_vendors($dbc, 'Checklist', 'subtab', $contype); echo (empty($cur_tab) ? '' : "($cur_tab)"); ?></option>

<option <?php if ($accr == "Description") { echo " selected"; } ?> value="Description"><?php echo get_field_config_vendors($dbc, 'Description', 'order', $contype, $subtab); ?> : Product Description</option>
<option <?php if ($accr == "Unique Identifier") { echo " selected"; } ?> value="Unique Identifier"><?php echo get_field_config_vendors($dbc, 'Unique Identifier', 'order', $contype); ?> : Unique Identifier</option>
<option <?php if ($accr == "Product Cost") { echo " selected"; } ?> value="Product Cost"><?php echo get_field_config_vendors($dbc, 'Product Cost', 'order', $contype); ?> : Product Cost</option>
<option <?php if ($accr == "Purchase Info") { echo " selected"; } ?> value="Purchase Info"><?php echo get_field_config_vendors($dbc, 'Purchase Info', 'order', $contype); ?> : Purchase Info</option>
<option <?php if ($accr == "Shipping Receiving") { echo " selected"; } ?> value="Shipping Receiving"><?php echo get_field_config_vendors($dbc, 'Shipping Receiving', 'order', $contype); ?> : Shipping Receiving</option>
<option <?php if ($accr == "Pricing") { echo " selected"; } ?> value="Pricing"><?php echo get_field_config_vendors($dbc, 'Pricing', 'order', $contype); ?> : Pricing</option>
<option <?php if ($accr == "Markup") { echo " selected"; } ?> value="Markup"><?php echo get_field_config_vendors($dbc, 'Markup', 'order', $contype); ?> : Markup</option>
<option <?php if ($accr == "Stock") { echo " selected"; } ?> value="Stock"><?php echo get_field_config_vendors($dbc, 'Stock', 'order', $contype); ?> : Stock</option>
<option <?php if ($accr == "Location") { echo " selected"; } ?> value="Location"><?php echo get_field_config_vendors($dbc, 'Location', 'order', $contype); ?> : Product Location</option>
<option <?php if ($accr == "Dimensions") { echo " selected"; } ?> value="Dimensions"><?php echo get_field_config_vendors($dbc, 'Dimensions', 'order', $contype); ?> : Dimensions</option>
<option <?php if ($accr == "Alerts") { echo " selected"; } ?> value="Alerts"><?php echo get_field_config_vendors($dbc, 'Alerts', 'order', $contype); ?> : Alerts</option>
<option <?php if ($accr == "Time Allocation") { echo " selected"; } ?> value="Time Allocation"><?php echo get_field_config_vendors($dbc, 'Time Allocation', 'order', $contype); ?> : Time Allocation</option>
<option <?php if ($accr == "Admin Fees") { echo " selected"; } ?> value="Admin Fees"><?php echo get_field_config_vendors($dbc, 'Admin Fees', 'order', $contype); ?> : Admin Fees</option>
<option <?php if ($accr == "Quote") { echo " selected"; } ?> value="Quote"><?php echo get_field_config_vendors($dbc, 'Quote', 'order', $contype); ?> : Quote</option>
<option <?php if ($accr == "Status") { echo " selected"; } ?> value="Status"><?php echo get_field_config_vendors($dbc, 'Status', 'order', $contype); ?> : Status</option>
<option <?php if ($accr == "General") { echo " selected"; } ?> value="General"><?php echo get_field_config_vendors($dbc, 'General', 'order', $contype); ?> : General</option>
<option <?php if ($accr == "Rental") { echo " selected"; } ?> value="Rental"><?php echo get_field_config_vendors($dbc, 'Rental', 'order', $contype); ?> : Rental</option>
<option <?php if ($accr == "Day/Week/Month/Year") { echo " selected"; } ?> value="Day/Week/Month/Year"><?php echo get_field_config_vendors($dbc, 'Day/Week/Month/Year', 'order', $contype); ?> : Day/Week/Month/Year</option>
<option <?php if ($accr == "Vehicle") { echo " selected"; } ?> value="Vehicle"><?php echo get_field_config_vendors($dbc, 'Vehicle', 'order', $contype); ?> : Vehicle</option>
<option <?php if ($accr == "Bill of Material") { echo " selected"; } ?> value="Bill of Material"><?php echo get_field_config_vendors($dbc, 'Bill of Material', 'order', $contype); ?> : Bill of Material</option>